# Generated by Django 5.0.1 on 2024-02-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='cover_image',
            field=models.ImageField(upload_to='recipes/cover/%Y/%m/%d/'),
        ),
    ]
